More fixes
Signed-off-by: Robert (Bobby) Evans <bobby@apache.org>

diff --git a/build/unapply-patches b/build/unapply-patches
--- a/build/unapply-patches
+++ b/build/unapply-patches
@@ -52,18 +52,23 @@ fi
 CHANGED_FILES=$(git status --porcelain --untracked-files=no)
 
 if [ \( -s "$FULLY_PATCHED_FILE" \) -a  \( -n "$CHANGED_FILES" \) ] ; then
-  echo "Patches appear to have been applied, so going to remove them"
-  patch -R --no-backup-if-mismatch -f -t --reject-file=- -p1 -i "$FULLY_PATCHED_FILE"
-  rm -f "$FULLY_PATCHED_FILE"
+  if git apply --check -R "$FULLY_PATCHED_FILE"; then
+    echo "Patches appear to have been applied, so going to remove them"
+    git apply -R -v "$FULLY_PATCHED_FILE"
+    rm -f "$FULLY_PATCHED_FILE"
 
-  # Check for modifications, again
-  if [ -n "$(git status --porcelain --untracked-files=no)" ] ; then
-    echo "Error: CUDF repository has uncommitted changes. You might want to clean in manually if you know that is expected"
-    git status --porcelain --untracked-files=no
+    # Check for modifications, again
+    if [ -n "$(git status --porcelain --untracked-files=no)" ] ; then
+      echo "Error: CUDF repository has uncommitted changes. You might want to clean in manually if you know that is expected"
+      git status --porcelain --untracked-files=no
+      exit 1
+    fi
+
+    exit 0
+  else
+    echo "Files are changed, but in a way where the full path file does not apply to remove them $FULL_PATCHED_FILE"
     exit 1
   fi
-
-  exit 0
 fi
 
 if [ -n "$CHANGED_FILES" ] ; then
